### ISSUE TITLE
Intent.Typescript.ServiceAgent.AngularJs and Intent.Typescript.ServiceAgent.Contracts Modules - Missing option to configure namespace

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/IntentArchitect#102]
On following templates:
- Intent.Typescript.ServiceAgent.Contracts.DTO.Local
- Intent.Typescript.ServiceAgent.AngularJs.Proxy.Local
- Intent.Typescript.ServiceAgent.AngularJs.Proxy.Remote

**Comment by garethbaars** [comment]
Hey @Carbz22, I believe we fixed this when we ran into the issue. Please confirm?

**Comment by Carbz22** [comment]
I do believe the fix you made the day covered this.
