### ISSUE TITLE
Feature Request: Snap to object in Canvas from Sidebar

### ISSUE THREAD

**Issue by mariusvrstr** [IntentSoftware/IntentArchitect#116]
Please look at adding the following:

**As a** intent user **I want to** double click on a object in the Model sidebar **so that** it focuses on the same object in the canvas.

This feature would work great with the search feature > taking you to the sidebar model (already doing this) then making it easy to find the domain entity/field in the actual model in the canvas.

**Comment by JonathanLydall** [comment]
The "Show in View" option from the context menu allows one to navigate to the element in the diagram.
