### ISSUE TITLE
DefaultFileMetaData class to use CodeGenType class to determine Code generation type

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#117]
Currently the `DefaultFileMetaData` class's constructor has a `string` parameter called "codeGenType". It allows one to refer to the `CodeGenType` class to use its constants to specify the desired Code Generation Type.
Could I suggest changing that parameter to accept an instance of `CodeGenType` where the class cannot be publicly instantiated but you refer to its `public static` options, instead of constant strings?
This will give it a more `Enum` feel and users won't have to guess or refer to documentation on what needs to go there (unless you actually want to convert it to an Enum).

**Comment by joelsteventurner** [comment]
This concept has gone through several evolutions, originally it was an enum. It currently an extensiblity point, i.e. you can associate a magic string which the template, which can then be targeted by cross cutting things like decorators or factory extensions. Where this probably should go is to become a collection of extensible stereotypes which can be applied to the template, and ideally editable through the UI in Intent Architect.

**Comment by dandrejvv** [comment]
Maybe have an overload method? 😅

**Comment by joelsteventurner** [comment]
That's a good interim solution, we might decide to bite the bullet and upgrade it to a StereoType or Tags system, with UI configurablility,  which is more inline with what it should be.

**Comment by dandrejvv** [comment]
Ok, in that case then rather go with your new plans because it will require strings anyway, right?

**Comment by joelsteventurner** [comment]
Either strings or something a little more extensible like stereotypes, but i think once we discuss it we'll probably settle on strings.
