### ISSUE TITLE
Create Application Templates blocked by Proxy

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#121]
It seems as though some parts of the application works well through a proxy and other parts do not.
The front-end is trying to fetch a list of templates that can be used to create new Intent Applications. The organisation proxy however is blocking it.

![image](https://user-images.githubusercontent.com/7236289/42512769-bd9c8854-8455-11e8-83a9-4f46d68a0529.png)

Error message logged:

> Request to https://intentarchitect.com/api/applicationtemplatemanager/searchapplicationtemplates failed with status code 401 Unauthorized.↵↵{"message":"Authorization has been denied for this request."}

Visiting that page using my normal browser gives me:
![image](https://user-images.githubusercontent.com/7236289/42513015-3478bcf4-8456-11e8-9e8d-55d1146e5ef8.png)

Even though it gives the error of "does not support GET", it shows that it is possible to visit that page using normal browser settings with the proxy configured by the OS.

Knowing that Intent uses a Chrome-like browser for its front end, is there some way to leverage the same browser proxy settings from the OS like I.E. and Chrome does?

**Comment by JonathanLydall** [comment]
The proxy in the "app.config" file affects the C# code, which the front end does use for a lot of things. However, my guess is that this screen is using Electron directly, which is not using the same proxy settings, we'll have to investigate further to find out what is happening.

**Comment by dandrejvv** [comment]
That's my suspicion. the browser in Electron is not leveraging the same proxy info like the other browsers do.

**Comment by dandrejvv** [comment]
This might be of use?

https://electronjs.org/docs/api/net

**Comment by dandrejvv** [comment]
I am not sure what happened but it seems to be working again. Both at work and on my personal laptop at home running 1.5.1
