### ISSUE TITLE
Issue with ASP.NET Core Startup.cs generation around services with duplicate operation names

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#128]
This should happen very seldom but it is worth pointing out.
Creating an ASP.NET Core application using Intent and creating two separate services but each having the exact same operation name causes a compiler error because it is trying to use two classes with the same name from two different namespaces and thus the compiler isn't sure which one to use.

So looking at the service model:
![image](https://user-images.githubusercontent.com/7236289/44302870-05744b80-a332-11e8-832c-11c17a6fd98a.png)

References the two namespaces like this (which is fine):
![image](https://user-images.githubusercontent.com/7236289/44302877-1c1aa280-a332-11e8-86ed-46fe68b760a8.png)

But doesn't apply the namespaces in these two lines in order to prevent ambiguity which causes the compiler to throw errors:
![image](https://user-images.githubusercontent.com/7236289/44302880-30f73600-a332-11e8-9350-ff08a3ef822f.png)

![image](https://user-images.githubusercontent.com/7236289/44302893-829fc080-a332-11e8-8727-7b3288b1bb6d.png)

**Comment by JonathanLydall** [comment]
A possible quick fix is to change the template such that it includes fully qualified names rather than adding usings.

However, it's possible in this case that the consumer of `ITemplateDependancy` is populating the usings and perhaps it can be made to be smart enough to understand how to avoid issues like this.

**Comment by garethbaars** [comment]
Hi @dandrejvv,

This issue has been fixed in the 1.6.0 version of the module `Intent.AspNetCore` which is now managing the Startup.cs file.

Please reopen this ticket if the problem persists.
