### ISSUE TITLE
Touchpad doesn't have way to scroll in Domain view

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#136]
If you are working off a laptop and you would like to scroll when you are on the Domain Class UML designer, then you are not able to since there is no middle button to scroll like with a normal mouse.
Potentially one could try and hook into some of the touchpad gestures to accomplish this?

**Comment by JonathanLydall** [comment]
Ctrl+Left Mouse Button also works for panning.

**Comment by dandrejvv** [comment]
It is working. Thanks.
