### ISSUE TITLE
EF 6 Mapping Concern

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/IntentArchitect#163]
For the following relationship:
![image](https://user-images.githubusercontent.com/1290262/54121307-cd824200-4402-11e9-8bb1-99631dc5a92a.png)

The generated EF mappings result in EF migrations wanting to create a superfluous `MainObjectId` column on the `SubObject` table. This generated column doesn't even have an FK constraint on it.

Generated mappings:
```csharp
    public partial class MainObjectMapping : EntityTypeConfiguration<MainObject>
    {

        public MainObjectMapping()
        {
            this.ToTable("MainObject");
            this.HasKey(x => x.Id);
            this.Property(x => x.Id).HasColumnName("Id");
            this.HasOptional(x => x.SubObject)
            .WithRequired(x => x.MainObject)
            .WillCascadeOnDelete()
            ;
        }
    }

    public partial class SubObjectMapping : EntityTypeConfiguration<SubObject>
    {

        public SubObjectMapping()
        {
            this.ToTable("SubObject");
            this.HasKey(x => x.Id);
            this.Property(x => x.Id).HasColumnName("Id");
        }
    }
```

Generated EF migration:
```csharp
    public partial class ChangeName : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.SubObject",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        MainObjectId = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.MainObject", t => t.Id, cascadeDelete: true)
                .Index(t => t.Id);
            
            CreateTable(
                "dbo.MainObject",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.SubObject", "Id", "dbo.MainObject");
            DropIndex("dbo.SubObject", new[] { "Id" });
            DropTable("dbo.MainObject");
            DropTable("dbo.SubObject");
        }
    }
```

**Comment by dandrejvv** [comment]
In your example, what you are saying is that the expected mapping should not have the column on the `SubObject`  entity but rather should be using the `MainObject`'s Id?

**Comment by JonathanLydall** [comment]
The issue is with the generated schema which looks like this:

[MainObject] Table:

- `[Id]` column

`[SubObject]` Table:

- `[Id]` column (which has FK onto `[MainObject].[Id]`
- `[MainObjectId]` column

So the immediately apparent issue is that the `[SubObject].[MainObjectId]` column has no FK constraint on it, as it's actually superfluous.

**Comment by dandrejvv** [comment]
I'm suspecting is should have produced the following mapping code:
```
public MainObjectMapping()
{
    this.ToTable("MainObject");
    this.HasKey(x => x.Id);
    this.Property(x => x.Id).HasColumnName("Id");
    this.HasOptional(x => x.SubObject)
        .WithOptionalPrincipal(x => x.MainObject)
        .WillCascadeOnDelete()
    ;
}
```

**Comment by dandrejvv** [comment]
Ok so the issue is that the Domain Entity is wrongfully generating the `MainObjectId` property. This is not necessary because the `MainObject` ID and `SubObject` ID are the same. It not only is a redundant property but it assumes that the `MainObject` ID is different. This is more suited for one-to-many associations.

**Comment by dandrejvv** [comment]
@JonathanLydall  would you please review the commit?

**Comment by JonathanLydall** [comment]
This has been merged back upstream.
