### ISSUE TITLE
Add IgnoreReason on IntentManaged attribute

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#165]
Please add an `IgnoreReason` property on the `IntentManaged` attribute so that a dev that overrides the Intent generated code can substantiate why it was set to `Ignore`. 
This will give the next developer some context as to why this was overridden without relying on comments because comments could be overridden by the software factory run.
This could in turn allow the Intent Software Factory to print out as warnings all those Ignore Reasons if one wishes to go that route.

**Comment by JonathanLydall** [comment]
@dandrejvv, have you considered adding a normal C# comment for your reason?

**Comment by dandrejvv** [comment]
Hi @JonathanLydall, as mentioned above, adding a normal C# comment can get overridden by a software factory run.

**Comment by JonathanLydall** [comment]
I see, thanks @dandrejvv.

@garethbaars, @joelsteventurner perhaps we should first look into why comments aren't maintained by RoslynWeaver and if that is not a better route to go down.

**Comment by JonathanLydall** [comment]
After group discussion, we'll add a `Reason` property to the attribute.

As a bonus, let's also try have it keep the comments.

**Comment by JonathanLydall** [comment]
Testing again, code comments _are_ maintained so this need can be met by that method.

In regards to adding a `Reason` property to the attribute, after discussion it's decided that while nice to have, it's technically complicated due to the way we find/parse these.

No plans to do at this time, closing issue.
