### ISSUE TITLE
Error when loading the Domain

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/IntentArchitect#21]
When trying to load the domain model I an error (detailed in the picture). Could be a result of the application I loaded not having a view in the domain.

![image](https://user-images.githubusercontent.com/8687460/30634070-17e01514-9dee-11e7-9b57-2ecdaeeac29a.png)

**Comment by garethbaars** [comment]
Associations which fail to load in the visual will be ignored. The model is still strictly required to load correctly.
