### ISSUE TITLE
Delete Not Working for "Model" Folder DTOs View

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/IntentArchitect#22]
I added a new "Model" (the name model seems a little weird in the context of the DTO view) folder to the DTOs view and when I tried to delete it via the context menu it wouldn't delete.

![image](https://user-images.githubusercontent.com/8687460/30639997-7a4a1462-9e01-11e7-9625-6b3e0b1e41d2.png)

**Comment by garethbaars** [comment]
fixed for next release
