### ISSUE TITLE
DTO/Services - Text Highlighting With Mouse

### ISSUE THREAD

**Issue by CraigForbes** [IntentSoftware/IntentArchitect#25]
When you rename a DTO/Service and try to highlight the text you want to select using the mouse, the whole element acts like you are trying to move it instead of allowing you to highlight.

![image](https://user-images.githubusercontent.com/17470616/30904417-3fee3912-a372-11e7-9c33-64d0a2f985fc.png)

**Comment by garethbaars** [comment]
fixed for 1.0.9-alpha
