### ISSUE TITLE
Specification no clause specified

### ISSUE THREAD

**Issue by Carbz22** [IntentSoftware/IntentArchitect#35]
I create a specification with two group statements in it. I specified that I want everything to return if no clauses were specified. The 'no clauses specified' still error throws. If I remove the group statements, the no clause behavior works as expected.

![image](https://user-images.githubusercontent.com/8687460/31766938-8f6c8698-b4c9-11e7-9ea3-42c136e00aa3.png)

**Comment by JonathanLydall** [comment]
This is fixed in the `Intent.Framework.Domain` NuGet package for versions >= `0.1.9-beta`.
