### ISSUE TITLE
Domain Loading Indicator

### ISSUE THREAD

**Issue by CraigForbes** [IntentSoftware/IntentArchitect#38]
It would be handy if we can see a loading indicator when you click on Domain in the side bar.
Sometimes it takes several seconds to load/appear on a large model but there is no indication anything is happening.

**Comment by dandrejvv** [comment]
The same can happen on DTO and Service pages when you have one folder expanded with lots of elements in them and you navigate between DTO and Service pages.

**Comment by garethbaars** [comment]
Agreed. We've done this for all the Modelers (DSLs) in V1.3
