### ISSUE TITLE
"Navigate to Type" option

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#44]
In the Services tab, one would find Types specified in the Request or Response elements. It would be great to have a "Navigate to Type" option on the Services tab which would (I guess it would ask you to save if anything changed?) jump to the DTOs tab and highlight the Type you selected in the Services tab.

For the DTOs tab it would also be beneficial to click on the type of a given property and navigate to the Type that is on another part of the page. Perhaps the Type on the Properties panel could have a button that would allow you to navigate to that Type.

**Comment by JonathanLydall** [comment]
Totally agree. We have already been discussing needing this kind of feature and have a few cool ideas towards it that we hope to be able to implement soon.

**Comment by dandrejvv** [comment]
Nice! Thanks.
