### ISSUE TITLE
DTO/Services "global" properties/settings

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#52]
What are your thoughts on having properties/settings that can be configured by clicking on the Root folder on DTOs and Services?
To add custom properties that can be used throughout Intent IDE and Modules? (Similar to how Stereotype properties are setup)

![image](https://user-images.githubusercontent.com/7236289/33984936-d5bc1338-e0c1-11e7-8085-881f6be9cda0.png)

**Comment by garethbaars** [comment]
Would having the ability to add stereotypes to the root package folders meet this need? We recognize that not being able to add stereotypes here is a bug as per #53

**Comment by joelsteventurner** [comment]
Another option is to model these as their own Custom Metadata.

**Comment by garethbaars** [comment]
That is a possibility, however running it through the Stereotype systems will allow it to be upgraded with the Stereotype systems. Stereotypes will eventually be able to support fixed collections, dropdowns,  dynamic lookups, etc., all of which could be very useful as properties on the root package folders. Unless there's a use case where the Stereotypes will not meet the requirement?

**Comment by joelsteventurner** [comment]
Depends on the Nature of the Data if it's truly global data i.e. across multiple DSLs / Metadata types, Custom Meta data is the route, in any other scenario Stereotypes is better.

**Comment by dandrejvv** [comment]
If I could add stereotypes on the root it would be cool as that would sort out my problem, at least how I look at it right now

**Comment by dandrejvv** [comment]
One could add a helper method to assist the module developers to find all the stereotypes in a folder hierarchy like this:

```c#
public static IEnumerable<IStereotype> FindAllStereotypes(this IDTOModel model)
{
    var itemsFound = new List<IStereotype>();

    itemsFound.AddRange(model.Stereotypes);

    IFolder cur = model.Folder;
    while(cur != null)
    {
        itemsFound.AddRange(cur.Stereotypes);
        cur = cur.ParentFolder;
    }

    return itemsFound;
}
```

So that you can just write:

```c#
Model.FindAllStereotypes().First(p => p.Name == "MyStereotype")
```

**Comment by garethbaars** [comment]
@dandrejvv, sure we can do something like that. Quick question: Would you expect the package root folder to be be considered a folder or it's own concept. (i.e. on a DTO under the root package folder, would you consider the root to be it's `.Folder` or its own concept, for example: `.Package`)

**Comment by dandrejvv** [comment]
@garethbaars as things currently stand I don't see it as anything different from a Folder.
I think if you can add Stereotypes to it, it should be sorted.
It is also easy to identify as root by checking that the Parent Folder is NULL.
I don't see the need just yet to complicate this structure.

**Comment by garethbaars** [comment]
As of 1.3-beta, stereotypes can now be added to the package folder. @dandrejvv, I'm going to close this ticket. Please reopen if this does not address your use case.
