### ISSUE TITLE
How can you add a stereotype to a root folder?

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#53]
In the DTOs section, when you right click on the root folder it presents the option to "Add Stereotype" but no matter what options you specify on stereotype definitions (in the DTO section), you can't add a stereotype to the root folder. Is this a bug or by design?

**Comment by garethbaars** [comment]
This is a bug. We will aim to fix for release 1.3.

**Comment by dandrejvv** [comment]
So the "root folder" is now called a `Package`. So now I can target Packages with my stereotypes now. Thanks!
