### ISSUE TITLE
Search-filter box on DTOs and Services

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#55]
It would be great to have the ability to lookup specific Services and DTOs by typing a partial name into a text box and the tree filters (or switches to a different result view) to be able to interact with that specific model item. You could place that search box on the same panel as the "save" button.

**Comment by garethbaars** [comment]
Hi @dandrejvv, there is definitely a need for a searching feature. The one option is as you describe, and similar to the inbuilt tree searching that comes with Visual Studio 2015/17. Another option is to do something similar to the ReSharper Ctrl+T search system, which brings up a small dialog that has powerful searching capabilities. We will be weighing up the pros and cons, but if you have a preference please let us know. Your reasoning would also be very helpful.

**Comment by dandrejvv** [comment]
It is a tough one I think which I think you would need to investigate. If I look for a stereotype I would like to see the child-components (i.e. sub properties) of the stereotype but if I look for a folder, would it be possible to view the child elements (on expansion) like sub-folders and sub-models?

**Comment by garethbaars** [comment]
Exactly, that's why I'm thinking more along the lines of modelling ReSharper's Ctrl+T functionality... it would just help _locate_ the element within the tree (and not hide any information)

**Comment by dandrejvv** [comment]
Potentially, thinking of the Domain screen, one could have a similar effect where you filter on the Models on the right and when you click on that, it jumps to the diagram element on the diagram. I think that would also be pretty useful?
