### ISSUE TITLE
Focus not on newly created element in tree

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#57]
In the DTO and Services tree, when one tried to add a new Service/DTO it doesn't place the focus on the newly created item (and bonus points, go straight into renaming mode).

**Comment by garethbaars** [comment]
Hi @dandrejvv, this feature is definitely on the road map. We built in this feature in an earlier release but disabled it because it had was causing other bugs. We will aim to get a robust solution in for 1.3...
