### ISSUE TITLE
Add Notes on Models in Intent IDE

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#60]
I think it would be very valuable to allow the Intent IDE user to add notes on Classes, Services, DTOs, Properties, etc. which will enable a couple of things:

- Model documentation: Explain the intent of a given model or model element when someone is looking at it from the Intent IDE.
- Source Code documentation: Whether it should be the same note concept or a different one, allow the modules to access the notes on a model to provide source code documentation during generation.

Please also add an icon to indicate that a given Model or Model element has a note.

**Comment by garethbaars** [comment]
Hey @dandrejvv, Totally agree. An alternative for the time being is to create a "Notes" (of whatever) stereotype with a property to capture your notes. You can enable the `Display Icon` checkbox to highlight that the element has a note on it. You could find the stereotype in your module to add the information as a code document. It may work out that enhancing the stereotypes to better suit this use case works better than building a feature specifically for documenting the elements. Let me know your thoughts...

**Comment by joelsteventurner** [comment]
Must agree, I think the Stereotype is the way to go, it also allows flexibility on how structured or un-structured you want your documentation to be, because you can define what the stereotypes look like.

**Comment by dandrejvv** [comment]
I will agree about generating documentation but if you want to make notes inside the Intent IDE, I think the Stereotype will have some drawbacks because maybe you want to allow a tooltip to display some notes when someone is hovering over the element, etc. or allow a popup dialog to be displayed when clicking on the notes element? This would also allow one to add some rich text formatting for the notes. Something similar to XMind (the mind mapping software).

What do you guys think? So maybe add an Intent Note concept as opposed to Code Documentation one?

**Comment by joelsteventurner** [comment]
Hmm, or maybe thats a new feature request :) Tooltips on stereo types, I like it.
There may be value in having a Comment concept in the DSL's, but I agree I wouldn't recommend using it for code gen, but could be useful for partial modelling / notes in the designer ?

**Comment by dandrejvv** [comment]
Exactly, I think it would be worthwhile giving some explanations on certain elements. Adding notes for Stereotypes could have tool-tips popping up the note with some explanation on what it would do, etc. and also adding notes on DSL Model elements (not for code-gen) to comment on why it is there, etc.

**Comment by JonathanLydall** [comment]
This was implemented in 1.6.0. The data is exposed through the metadata as well.
