### ISSUE TITLE
Type Lookup to include Folder path

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#70]
Currently with the Type lookup drop-down, if there are types that are duplicates by name, there is no way to distinguish between them. One way to solve this problem is to provide a folder path right next to them in way that makes sense so that one can distinguish between them.

So if you have folders like:
 - Personal
   + Entities
 - Business
   + Entities

And both have them have distinct `Address` DTOs:

![image](https://user-images.githubusercontent.com/7236289/34770413-c4b95b4c-f609-11e7-9219-f7b9aed390ee.png)
  
I'm not sure what would be best if the folder path becomes too long. Perhaps work from the root folder?

**Comment by JonathanLydall** [comment]
Agreed that we definitely need _some_ way of distinguishing. While tackling
this we should also consider that it could be from separate packages,
possibly with the same folder names.

**Comment by dandrejvv** [comment]
Would it be possible to have it bring up a tooltip to show the complete path?

**Comment by JonathanLydall** [comment]
That would likely be ideal and I had the same idea myself. If the combo box control we are using supports adding a tool tip then it would be quite easy to implement, otherwise it would be a major task to add a tool tip.

**Comment by dandrejvv** [comment]
Although, with the new packaging system, would it be beneficial to filter the DTOs by Package?

**Comment by dandrejvv** [comment]
Very nice! Thanks!
