### ISSUE TITLE
Deleting a DTO that is linked to a Service can break the app

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#72]
Version : 1.2-beta

If you delete a `DTO` that is referenced to a `Service` operation and you save, and you open the `Services` it will break the application.

    ApplicationDTOLoader - DTO [<DTO that is deleted>] has a field without a type in application <Application Name>"

**Comment by garethbaars** [comment]
Hi @dandrejvv, this should be fixed implicitly in v1.3 as we will no longer be loading outside DSLs into a DSL (e.g. loading DTOs into Services). All required packages will need to be loaded into the DSL for the types to be accessible. We therefore will be loading all the DTO packages into the Services as part of the v1.3 migration.
