### ISSUE TITLE
Need a way to sort Service operations alphabetically

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#74]
With the ability to order Service operations to any custom order is great but we certainly need a way to order Service operations alphabetically

**Comment by garethbaars** [comment]
We could support this by adding a sort function to the context menu on the Services (i.e. Sort A-Z). That way one could opt in to the sorting as and when needed. The sorting wont be maintained though - it will only be applied once, at the time the function is clicked.

**Comment by dandrejvv** [comment]
@garethbaars totally happy with that. Thanks!

**Comment by dandrejvv** [comment]
Cool stuff, thanks for that!
