### ISSUE TITLE
Add Mapping capability on other Services

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#94]
Using something similar to the Domain to DTO mapper, could it be done so that one can map off another Service with DTOs? This will work great for scenarios where you have an Adapter service which is for internal use but you don't want to expose that service externally and so you have another Externally facing service that looks very similar to the Adapter service by using the mapping functionality to get the initial contracts the same. This could even assist with doing DTO to DTO mapping as well.

**Comment by JonathanLydall** [comment]
Implemented with 1.6.0.
