### ISSUE TITLE
Copy and Paste DTOs

### ISSUE THREAD

**Issue by dandrejvv** [IntentSoftware/IntentArchitect#95]
It would be useful to Copy and Paste DTOs in the Services screen.
Some DTOs that one is working on would look very similar to others apart from the name.
So you would copy an existing DTO, and paste it in the some folder. If there is a DTO in that folder with the same name, it should add some unique differentiator to the pasted DTO's name like Visual Studio would.
All the fields and stereotypes should be copied as well.

**Comment by garethbaars** [comment]
Hi @dandrejvv, this feature is definitely on our backlog (for all elements). At the moment, we have a certain level of support for this: if you hold down Ctrl and drag the DTO (or any element for that matter) into a folder it will copy it.
